roboclaw_wrapper:
  ros__parameters:
    drive_acceleration_factor: 0.8
    corner_acceleration_factor: 0.8
    velocity_timeout: 2.0
    baud_rate: 115200
    device: "/dev/serial0"
    addresses: [128, 129, 130]  # Note que removi 130 porque só tem 2 controladores agora
    duty_mode: false
    velocity_qpps_to_duty_factor: 8
    roboclaw_mapping:
      drive_left_front:
        address: 128
        channel: M1
        ticks_per_rev: 48
        gear_ratio: 171.79
      drive_left_back:
        address: 129
        channel: M2
        ticks_per_rev: -48
        gear_ratio: 171.79
      drive_right_back:
        address: 129
        channel: M1
        ticks_per_rev: 48
        gear_ratio: 171.79
      drive_right_front:
        address: 130
        channel: M2
        ticks_per_rev: 48
        gear_ratio: 171.79
